# Generated by Django 4.2.15 on 2024-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
